services:
  nat:
    image: nat-nim-handson:1.6.0
    env_file:
      - .env
    networks:
      - langfuse_default
      - milvus_default
    volumes:
      - ./workflow.yml:/app/workflows/workflow.yml:ro
      - ./graphs:/app/graphs:ro
    command:
      - "run"
      - "--config_file"
      - "/app/workflows/workflow.yml"
      - "--input"
      - "VPN の利用ガイドラインは？"

networks:
  langfuse_default:
    external: true
  milvus_default:
    external: true
    name: ch06-rag-milvus_default
