services:
  nat:
    image: nat-nim-handson:1.6.0
    env_file:
      - .env
    networks:
      - langfuse_default
    volumes:
      - ./workflow.yml:/app/workflows/workflow.yml:ro
    command:
      - "run"
      - "--config_file"
      - "/app/workflows/workflow.yml"
      - "--input"
      - "What is today's date?"

networks:
  langfuse_default:
    external: true
